@extends('app')
@section('content')
    <div class="row page-boxer">
        <h3 class="lsi-header text-center" style="padding:15px"><span>Terms &amp; Conditions</span></h3>
        <div class="body-page-boxer container">
            <div class="col-xs-12 alert-info static-page navbar">
                <p>Welcome to {{ $_SERVER['HTTP_HOST'] }}! This agreement sets forth the terms on which you may access and use our services. The services offered by {{ $_SERVER['HTTP_HOST'] }} include the&nbsp;{{ $_SERVER['HTTP_HOST'] }} website (the “Site”) and any other features, content offered from time to time by {{ $_SERVER['HTTP_HOST'] }} in connection with the Site (collectively, the “{{ $_SERVER['HTTP_HOST'] }} Services”).</p>

                <p>By accessing or using the Site, you agree to be bound by the following terms and conditions and policies, including any future amendments (collectively, the “Terms of Use” or “Agreement”).</p>

                <p>READ THESE TERMS OF USE: THEY ARE IMPORTANT! THESE TERMS OF USE CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THE&nbsp;{{ $_SERVER['HTTP_HOST'] }} SERVICES.</p>

                <p>Nothing in these Terms of Use should be construed to confer any rights to third-party beneficiaries.</p>

                <p>We reserve the right, at our sole discretion, to change, modify, add, or delete portions of the Terms of Use at any time without further notice, without liability to you, any other member or any third-party. If we do this, we will post the changes to the Terms of Use on this page and will indicate at the top of this page the date these terms were last revised. Your continued use of the&nbsp;{{ $_SERVER['HTTP_HOST'] }} Services after any such changes constitutes your acceptance of the new Terms of Use. If you do not agree to abide by these or any future Terms of Use, then please do not access or use (or continue to access or use) the&nbsp;{{ $_SERVER['HTTP_HOST'] }} Services. It is your responsibility to regularly check the Site to determine if there have been changes to these Terms of Use and to carefully review such changes.</p>

                <p><strong>Eligibility/Use of Service</strong></p>

                <p>Your use of the&nbsp;{{ $_SERVER['HTTP_HOST'] }} Services is governed by these Terms of Use. You must be at least 18 years of age to use the {{ $_SERVER['HTTP_HOST'] }} Services. Any use of or access to the {{ $_SERVER['HTTP_HOST'] }} Services by anyone under the age of 18 is unauthorized, unlicensed and in violation of these Terms of Use. By using the {{ $_SERVER['HTTP_HOST'] }} Services, you represent and warrant that you are 18 years of age or older and that you agree to and to abide by all of the terms and conditions of this Agreement.</p>

                <p>{{ $_SERVER['HTTP_HOST'] }} reserves the right to refuse service without prior notice to anyone at any time for any or no reason.</p>

                <p><strong>Privacy Policy</strong></p>

                <p>By using or accessing the Site or the {{ $_SERVER['HTTP_HOST'] }} Services, you are consenting to have your personal data transferred to and YOU ARE ASSENTING TO THE TERMS AND CONDITIONS OF {{ $_SERVER['HTTP_HOST'] }}’S PRIVACY POLICY, WHICH IS LOCATED AT&nbsp;&nbsp;<a href="{{ url('/policy') }}">PRIVACY POLICY</a>&nbsp;AND WHICH CONSTITUTES PART OF THIS AGREEMENT.</p>

                <p><strong>Links to Third-Party Websites and Content</strong></p>

                <p>The {{ $_SERVER['HTTP_HOST'] }} Services contain links to other websites that are not owned or controlled by {{ $_SERVER['HTTP_HOST'] }} (“Third-Party Websites”) as well as photographs, text, graphics, pictures, designs, music, sound, video, information and other content belonging to or originating from third-parties (the “Third-Party Content”). {{ $_SERVER['HTTP_HOST'] }} has no control over, and assumes no responsibility for any Third-Party Websites accessed through the {{ $_SERVER['HTTP_HOST'] }} Services, or any Third-party Content posted on the {{ $_SERVER['HTTP_HOST'] }} Services, including without limitation the content, accuracy, offensiveness, opinions, reliability or policies of or contained in the Third-Party Websites or the Third-Party Content. {{ $_SERVER['HTTP_HOST'] }} does not investigate, monitor, edit, or censor any Third-Party Websites or Third-Party Content. Inclusion of or linking to any Third-Party Website or any Third-Party Content does not imply approval or endorsement thereof by {{ $_SERVER['HTTP_HOST'] }}. When clicking on coupon codes or other links to merchants on the {{ $_SERVER['HTTP_HOST'] }} site, you will be sent directly to the merchant’s site to complete your transaction.</p>

                <p>We encourage you to be aware when you leave the {{ $_SERVER['HTTP_HOST'] }} Services, and access any Third-Party Websites. If you leave the {{ $_SERVER['HTTP_HOST'] }} Services and access any Third-Party Websites, be mindful that our terms and policies no longer govern, and that you do so at your own risk. You should review the applicable terms and policies, including privacy and data gathering practices, of any Third-Party Websites that you visit.</p>

                <p><strong>Intellectual Property Rights</strong></p>

                <p>The content on the {{ $_SERVER['HTTP_HOST'] }} Services including without limitation, the text, graphics, photos, videos, interactive features, and the like, and their selection and arrangement (“Content”) and the trademarks, service marks and logos contained therein (“Marks”), are owned by or licensed to {{ $_SERVER['HTTP_HOST'] }}, subject to copyright and other intellectual property rights. All content on the Site is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, modified, downloaded, posted, sold, licensed, or otherwise exploited for any other purposes whatsoever, in any form or by any means, without the prior written consent of the respective owners. {{ $_SERVER['HTTP_HOST'] }} reserves all rights not expressly granted in and to the {{ $_SERVER['HTTP_HOST'] }} Services and the Content. You agree to not engage in the use, copying, or distribution of any of the Content other than as expressly permitted herein, including any use, copying, or distribution of content of third-parties obtained through the {{ $_SERVER['HTTP_HOST'] }} Services for any commercial purposes. If you download or print a copy of the Content for personal use, you must retain all copyright and other proprietary notices contained therein. You agree not to circumvent, disable or otherwise interfere with security related features of the {{ $_SERVER['HTTP_HOST'] }} Services or features that prevent or restrict use or copying of any Content or enforce limitations on use of the {{ $_SERVER['HTTP_HOST'] }} Services or the Content therein. Any use of Content other than as specifically authorized herein, without the prior written consent of the respective owners, is strictly prohibited. Be aware that unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. Nothing herein shall be construed as conferring any license to the intellectual property rights of any third-party, whether by estoppel, implication or otherwise.</p>

                <p>Except as expressly authorized by {{ $_SERVER['HTTP_HOST'] }}, you may not copy, modify, publish, transmit, distribute, perform, display or sell any of {{ $_SERVER['HTTP_HOST'] }}’s proprietary information.</p>

                <p><strong>User Conduct</strong></p>

                <p>The {{ $_SERVER['HTTP_HOST'] }} Services (including the Site) are available for your personal, non-commercial use only. You represent, warrant and agree that no materials of any kind submitted, posted or shared by you through the {{ $_SERVER['HTTP_HOST'] }} Services will violate or infringe upon the rights of any third-party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libelous, defamatory or otherwise unlawful material. You further agree not to harvest or collect email addresses or other contact information of users from the {{ $_SERVER['HTTP_HOST'] }} Services by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications. Additionally, you agree not to use any software or automated systems or scripts to collect information or Content from the {{ $_SERVER['HTTP_HOST'] }} Services for any purpose. You further agree that you will not use the {{ $_SERVER['HTTP_HOST'] }} Services in any unlawful manner or in any other manner that could damage, disable, overburden or impair the {{ $_SERVER['HTTP_HOST'] }} Services. In addition, you agree not to use the {{ $_SERVER['HTTP_HOST'] }} Services or the Site to:</p>

                <ul>
                    <li>impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with any person or entity;</li>
                    <li>interfere with, disrupt, impair or create an undue burden on the {{ $_SERVER['HTTP_HOST'] }} Services or the networks or services connected to the {{ $_SERVER['HTTP_HOST'] }} Services;</li>
                    <li>upload, post, transmit, share or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
                    <li>use the {{ $_SERVER['HTTP_HOST'] }} Services in a manner inconsistent with any applicable laws or regulations</li>
                </ul>

                <p>{{ $_SERVER['HTTP_HOST'] }} permits you to link to materials on the Site for personal, non-commercial purposes only. {{ $_SERVER['HTTP_HOST'] }} reserves the right to discontinue any aspect of the {{ $_SERVER['HTTP_HOST'] }} Services at any time.</p>

                <p><strong>Warranty Disclaimer</strong></p>

                <p>YOU AGREE THAT YOUR USE OF THE {{ $_SERVER['HTTP_HOST'] }} SERVICES, INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE, SHALL BE AT YOUR SOLE RISK. THE {{ $_SERVER['HTTP_HOST'] }} SERVICES, {{ $_SERVER['HTTP_HOST'] }} WEBSITE AND CONTENT ARE PROVIDED “AS IS.” TO THE FULLEST EXTENT PERMITTED BY LAW, {{ $_SERVER['HTTP_HOST'] }} , ITS SUBSIDIARIES, PARENTS AND AFFILIATES, AND EACH OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE {{ $_SERVER['HTTP_HOST'] }} SERVICES AND YOUR USE THEREOF. {{ $_SERVER['HTTP_HOST'] }} MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE {{ $_SERVER['HTTP_HOST'] }} SERVICE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE {{ $_SERVER['HTTP_HOST'] }} SERVICES AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE {{ $_SERVER['HTTP_HOST'] }} SERVICES OR {{ $_SERVER['HTTP_HOST'] }} WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE {{ $_SERVER['HTTP_HOST'] }} SERVICES, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE {{ $_SERVER['HTTP_HOST'] }} SERVICES OR {{ $_SERVER['HTTP_HOST'] }} ‘S SERVERS BY ANY THIRD-PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE {{ $_SERVER['HTTP_HOST'] }} SERVICES. {{ $_SERVER['HTTP_HOST'] }} DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD-PARTY THROUGH THE {{ $_SERVER['HTTP_HOST'] }} SERVICES OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND {{ $_SERVER['HTTP_HOST'] }} WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF ANY PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>

                <p>{{ $_SERVER['HTTP_HOST'] }}, its parents, subsidiaries, and affiliates, and their respective officers, directors, employees, and agents, are not responsible or liable in any manner for any Third-Party Content posted, uploaded, or displayed on the Site or in connection with the {{ $_SERVER['HTTP_HOST'] }} Services, whether caused by users of the {{ $_SERVER['HTTP_HOST'] }} Services or by any of the equipment or programming associated with or utilized in the {{ $_SERVER['HTTP_HOST'] }} Services. Although we provide rules for user conduct, we do not control and are not responsible for what third-parties post on the {{ $_SERVER['HTTP_HOST'] }} Services and are not responsible for any offensive, inappropriate, obscene, unlawful or otherwise objectionable content you may encounter on the {{ $_SERVER['HTTP_HOST'] }} Services or in connection with any Third-party Content. {{ $_SERVER['HTTP_HOST'] }}, its parent company, subsidiaries, and affiliates, and their respective officers, directors, employees, and agents, are not responsible for the conduct, whether online or offline, of any user of the {{ $_SERVER['HTTP_HOST'] }} Services.</p>

                <p>The {{ $_SERVER['HTTP_HOST'] }} Services may be temporarily unavailable from time to time for maintenance or other reasons. {{ $_SERVER['HTTP_HOST'] }} assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user communications. {{ $_SERVER['HTTP_HOST'] }} is not responsible for any problems or technical malfunction of any telephone network or lines, computer systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any website or combination thereof, including injury or damage to users or to any other person’s computer related to or resulting from participating or downloading materials in connection with the {{ $_SERVER['HTTP_HOST'] }} Services. Under no circumstances will {{ $_SERVER['HTTP_HOST'] }} be responsible for any loss or damage, including any loss or personal injury or death resulting from anyone’s use of the {{ $_SERVER['HTTP_HOST'] }} Services, any Third-Party Content posted on or through the {{ $_SERVER['HTTP_HOST'] }} Services or transmitted to users of the {{ $_SERVER['HTTP_HOST'] }} Services, or any interactions between users of the {{ $_SERVER['HTTP_HOST'] }} Services, whether online or offline.</p>

                <p><strong>Limitation of Liability</strong></p>

                <p>IN NO EVENT SHALL {{ $_SERVER['HTTP_HOST'] }}, ITS SUBSIDIARIES, PARENTS OR AFFILIATES, OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING ANY LOST PROFITS OR LOST DATA, RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE {{ $_SERVER['HTTP_HOST'] }} SERVICES (INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE), (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE {{ $_SERVER['HTTP_HOST'] }} SERVICES (INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE), (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH THE {{ $_SERVER['HTTP_HOST'] }} SERVICES (INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE) BY ANY THIRD-PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE {{ $_SERVER['HTTP_HOST'] }} SERVICES (INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE), WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT {{ $_SERVER['HTTP_HOST'] }} IS AWARE OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>

                <p>YOU SPECIFICALLY ACKNOWLEDGE THAT {{ $_SERVER['HTTP_HOST'] }} SHALL NOT BE LIABLE FOR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD-PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>

                <p>EXCEPT IN JURISDICTIONS WHERE SUCH PROVISIONS ARE RESTRICTED, IN NO EVENT WILL {{ $_SERVER['HTTP_HOST'] }}, ITS SUBSIDIARIES, PARENTS OR AFFILIATES, OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU OR ANY THIRD-PERSON FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA ARISING FROM YOUR USE OF THE {{ $_SERVER['HTTP_HOST'] }} SERVICES (INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE) OR ANY OF THE CONTENT OR OTHER MATERIALS ON OR ACCESSED THROUGH THE {{ $_SERVER['HTTP_HOST'] }} SERVICES (INCLUDING THE {{ $_SERVER['HTTP_HOST'] }} WEBSITE), EVEN IF {{ $_SERVER['HTTP_HOST'] }} IS AWARE OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

                <p>NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, {{ $_SERVER['HTTP_HOST'] }}’S LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO {{ $_SERVER['HTTP_HOST'] }} FOR THE SERVICE DURING THE TERM OF MEMBERSHIP, BUT IN NO CASE WILL {{ $_SERVER['HTTP_HOST'] }}’S LIABILITY TO YOU EXCEED $50. YOU ACKNOWLEDGE THAT IF NO FEES ARE PAID TO {{ $_SERVER['HTTP_HOST'] }} FOR THE SERVICE, YOU SHALL BE LIMITED TO INJUNCTIVE RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND SHALL NOT BE ENTITLED TO DAMAGES OF ANY KIND FROM {{ $_SERVER['HTTP_HOST'] }}, REGARDLESS OF THE CAUSE OF ACTION.</p>

                <p>CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>

                <p><strong>Release</strong></p>

                <p>You are solely responsible for your interactions with other {{ $_SERVER['HTTP_HOST'] }} users and third-party providers of products or services. {{ $_SERVER['HTTP_HOST'] }} reserves the right, but has no obligation or duty, to monitor disputes between you and other users.</p>

                <p>IF YOU HAVE A DISPUTE WITH ANY THIRD-PARTY PROVIDER OF PRODUCTS OR SERVICES, YOU RELEASE {{ $_SERVER['HTTP_HOST'] }}, ITS PARENTS, SUBSIDIARIES, AND AFFILIATES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES.</p>

                <p><strong>Indemnity</strong></p>

                <p>You agree to defend, indemnify and hold harmless {{ $_SERVER['HTTP_HOST'] }}, its subsidiaries, parents and affiliates, and each of their officers, directors, partners, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) your use of and access to the Site or other {{ $_SERVER['HTTP_HOST'] }} Services; (ii) your violation of any term of these Terms of Use or of any applicable law; (iii) your violation of any third-party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that one of your use of the site caused damage to a third-party. This defense and indemnification obligation will survive these Terms of Use and your use of the {{ $_SERVER['HTTP_HOST'] }} Services.</p>

                <p><strong>Ability to Accept Terms of Use</strong></p>

                <p>You affirm that you are more than 18 years of age and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set fo</p>
            </div>
        </div>
    </div>
@endsection